ALTER TABLE users ADD reactions BIGINT NOT NULL DEFAULT 0;
ALTER TABLE users ADD tips BIGINT NOT NULL DEFAULT 0;
ALTER TABLE users ADD live_comments BIGINT NOT NULL DEFAULT 0;

ALTER TABLE livestreams ADD reactions BIGINT NOT NULL DEFAULT 0;
ALTER TABLE livestreams ADD tips BIGINT NOT NULL DEFAULT 0;
ALTER TABLE livestreams ADD max_tip BIGINT NOT NULL DEFAULT 0;
